#!/bin/bash

# Stage 5 Deployment Commands
# Run these commands in order to deploy Stage 5 to production

echo "=========================================="
echo "Stage 5 Deployment - Command Reference"
echo "=========================================="
echo ""

echo "STEP 1: Verify Implementation Locally"
echo "--------------------------------------"
echo "node scripts/verify-stage5.mjs"
echo ""
echo "Expected: 71/71 tests passed"
echo ""

echo "STEP 2: Verify Stage 4 Regression"
echo "--------------------------------------"
echo "node scripts/verify-stage4.mjs"
echo ""
echo "Expected: 41/41 tests passed"
echo ""

echo "STEP 3: Apply Database Migration"
echo "--------------------------------------"
echo "# Option A: Supabase CLI"
echo "supabase db push"
echo ""
echo "# Option B: Supabase SQL Editor"
echo "# 1. Open Supabase dashboard → SQL Editor"
echo "# 2. Copy contents of: supabase/migrations/004_stage5_attribution_and_conversions.sql"
echo "# 3. Execute"
echo ""

echo "STEP 4: Set Environment Variables (Optional)"
echo "--------------------------------------"
echo "# Google Ads (optional - degrades gracefully if missing)"
echo "vercel env add GOOGLE_ADS_CUSTOMER_ID production"
echo "vercel env add GOOGLE_ADS_CONVERSION_ACTION_ID production"
echo "vercel env add GOOGLE_ADS_DEVELOPER_TOKEN production"
echo "vercel env add GOOGLE_ADS_CLIENT_ID production"
echo "vercel env add GOOGLE_ADS_CLIENT_SECRET production"
echo "vercel env add GOOGLE_ADS_REFRESH_TOKEN production"
echo ""
echo "# Meta CAPI (optional - degrades gracefully if missing)"
echo "vercel env add META_PIXEL_ID production"
echo "vercel env add META_CAPI_ACCESS_TOKEN production"
echo ""
echo "# Admin (optional - for metrics endpoint)"
echo "vercel env add ADMIN_SECRET production"
echo ""

echo "STEP 5: Commit and Deploy"
echo "--------------------------------------"
echo "git add -A"
echo "git commit -m \"Stage 5: Ads Launch Hardening & Conversion Integrity\""
echo "git push origin main"
echo "vercel --prod"
echo ""

echo "STEP 6: Verify Production Deployment"
echo "--------------------------------------"
echo "# Test attribution capture"
echo "curl -X POST https://yourdomain.com/api/leads \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"Referer: https://google.com/?gclid=test123\" \\"
echo "  -d '{\"email\":\"test@example.com\",\"full_name\":\"Test User\",...}'"
echo ""
echo "# Check if attribution was captured"
echo "# In Supabase SQL Editor:"
echo "# SELECT * FROM attribution_events ORDER BY created_at DESC LIMIT 10;"
echo ""
echo "# Test metrics endpoint"
echo "curl \"https://yourdomain.com/api/metrics/summary?secret=YOUR_CRON_SECRET\""
echo ""
echo "# Manual trigger conversion worker"
echo "curl \"https://yourdomain.com/api/workers/conversions?secret=YOUR_CRON_SECRET\""
echo ""

echo "STEP 7: Verify in Production Database"
echo "--------------------------------------"
echo "# In Supabase SQL Editor, run:"
echo ""
echo "-- Check attribution events"
echo "SELECT COUNT(*) FROM attribution_events;"
echo "SELECT * FROM attribution_events ORDER BY created_at DESC LIMIT 5;"
echo ""
echo "-- Check conversion events"
echo "SELECT COUNT(*) FROM conversion_events;"
echo "SELECT status, provider, COUNT(*) FROM conversion_events GROUP BY status, provider;"
echo ""
echo "-- Check suspicious events"
echo "SELECT reason_code, COUNT(*) FROM suspicious_events"
echo "WHERE created_at > NOW() - INTERVAL '24 hours'"
echo "GROUP BY reason_code;"
echo ""

echo "=========================================="
echo "Deployment Complete!"
echo "=========================================="
echo ""
echo "📚 Documentation:"
echo "  - Full Report: STAGE-5-VERIFICATION-REPORT.md"
echo "  - Summary: STAGE-5-SUMMARY.md"
echo "  - Final Report: STAGE-5-FINAL-REPORT.md"
echo ""
echo "✅ Verification Results:"
echo "  - Stage 5: 71/71 tests passed"
echo "  - Stage 4: 41/41 tests passed"
echo "  - Total: 112/112 tests passed (100%)"
echo ""
echo "🚀 Ready for production!"
