export const COUNTRIES = [
  { code: 'AE', name: 'United Arab Emirates', callingCode: '+971', flag: '🇦🇪' },
  { code: 'US', name: 'United States', callingCode: '+1', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', callingCode: '+44', flag: '🇬🇧' },
  { code: 'SA', name: 'Saudi Arabia', callingCode: '+966', flag: '🇸🇦' },
  { code: 'QA', name: 'Qatar', callingCode: '+974', flag: '🇶🇦' },
  { code: 'KW', name: 'Kuwait', callingCode: '+965', flag: '🇰🇼' },
  { code: 'BH', name: 'Bahrain', callingCode: '+973', flag: '🇧🇭' },
  { code: 'OM', name: 'Oman', callingCode: '+968', flag: '🇴🇲' },
  { code: 'IN', name: 'India', callingCode: '+91', flag: '🇮🇳' },
  { code: 'PK', name: 'Pakistan', callingCode: '+92', flag: '🇵🇰' },
  { code: 'EG', name: 'Egypt', callingCode: '+20', flag: '🇪🇬' },
  { code: 'AU', name: 'Australia', callingCode: '+61', flag: '🇦🇺' },
  { code: 'CA', name: 'Canada', callingCode: '+1', flag: '🇨🇦' },
  { code: 'DE', name: 'Germany', callingCode: '+49', flag: '🇩🇪' },
  { code: 'FR', name: 'France', callingCode: '+33', flag: '🇫🇷' },
  { code: 'IT', name: 'Italy', callingCode: '+39', flag: '🇮🇹' },
  { code: 'ES', name: 'Spain', callingCode: '+34', flag: '🇪🇸' },
  { code: 'NL', name: 'Netherlands', callingCode: '+31', flag: '🇳🇱' },
  { code: 'CN', name: 'China', callingCode: '+86', flag: '🇨🇳' },
  { code: 'JP', name: 'Japan', callingCode: '+81', flag: '🇯🇵' },
  { code: 'SG', name: 'Singapore', callingCode: '+65', flag: '🇸🇬' },
  { code: 'MY', name: 'Malaysia', callingCode: '+60', flag: '🇲🇾' },
  { code: 'TH', name: 'Thailand', callingCode: '+66', flag: '🇹🇭' },
  { code: 'PH', name: 'Philippines', callingCode: '+63', flag: '🇵🇭' },
  { code: 'ID', name: 'Indonesia', callingCode: '+62', flag: '🇮🇩' },
  { code: 'BD', name: 'Bangladesh', callingCode: '+880', flag: '🇧🇩' },
  { code: 'LK', name: 'Sri Lanka', callingCode: '+94', flag: '🇱🇰' },
  { code: 'NP', name: 'Nepal', callingCode: '+977', flag: '🇳🇵' },
  { code: 'ZA', name: 'South Africa', callingCode: '+27', flag: '🇿🇦' },
  { code: 'NG', name: 'Nigeria', callingCode: '+234', flag: '🇳🇬' },
  { code: 'KE', name: 'Kenya', callingCode: '+254', flag: '🇰🇪' },
  { code: 'BR', name: 'Brazil', callingCode: '+55', flag: '🇧🇷' },
  { code: 'MX', name: 'Mexico', callingCode: '+52', flag: '🇲🇽' },
  { code: 'AR', name: 'Argentina', callingCode: '+54', flag: '🇦🇷' },
  { code: 'TR', name: 'Turkey', callingCode: '+90', flag: '🇹🇷' },
  { code: 'RU', name: 'Russia', callingCode: '+7', flag: '🇷🇺' },
  { code: 'KR', name: 'South Korea', callingCode: '+82', flag: '🇰🇷' },
  { code: 'VN', name: 'Vietnam', callingCode: '+84', flag: '🇻🇳' },
];

export type Country = typeof COUNTRIES[number];
